server:
  port: 9090
secret:
  mail:
    username: anyname@gmail.com
    password: password
message:
  success: 'Config server is working uuuu
  error: 'Config server is not working ...yyyy'
spring:          
  rabbitmq:
    port: 4672
    host: localhost
    username: guest
    password: guest  
